// import localFont from "next/font/local";
import Header from "../_components/header/Header";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      
        className={`bg-dark text-textColor font-bold  antialiased`}
      >
        <div dir="rtl">
        <Header/>
        {children}
        </div>

      </body>
    </html>
  );
}
